plugins { id 'com.android.application' }

android {
    namespace 'com.rokid.scanvision.phone'
    compileSdk 34

    defaultConfig {
        applicationId 'com.rokid.scanvision.phone'
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies {
    implementation 'com.rokid.cxr:client-l:1.1.1'
}
