plugins { id 'com.android.application' }

android {
    namespace 'com.rokid.scanvision.glasses'
    compileSdk 34

    defaultConfig {
        applicationId 'com.rokid.scanvision.glasses'
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies {
    implementation 'com.rokid.cxr:cxr-service-bridge:1.0-20260728.074302-110'
}
